version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: notdrlazarus/virusscanapi:latest
    container_name: "virusscanapi-container"
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - /home/ec2-user/Cloudsine/VirusScanGateway/ssl/certs/domain.cert.pem:/app/ssl/certs/domain.cert.pem:ro
      - /home/ec2-user/Cloudsine/VirusScanGateway/ssl/certs/private.key.pem:/app/ssl/certs/private.key.pem:ro
