name: Go App CI/CD for Non-Main Branches

on:
  push:
    branches-ignore:
      - "main"
  pull_request:
    branches:
      - "*"

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.21.4"
      - name: Build and run Docker container
        run: |
          docker-compose -f docker-compose-dev-CICD.yml build
          docker-compose -f docker-compose-dev-CICD.yml up -d
      - name: Wait for App to be Ready
        run: |
          for i in {1..30}; do
            response=$(curl -s -o response.txt -w "%{http_code}" 127.0.0.1:8080/)
            echo "HTTP Status: $response"
            if [ "$response" -eq 200 ]; then
              echo "App is up and running. Response:"
              cat response.txt
              break
            else
              echo "Waiting for app to be ready..."
              sleep 10
            fi
          done

      - name: Run tests
        run: go test -v ./servertest

      - name: Cleanup Docker
        run: |
          docker-compose -f docker-compose-dev-CICD.yml down -v
          docker container prune -f
          docker image prune -f

      - name: Check test results
        if: ${{ failure() }}
        run: exit 1
