name: Build and deploy a container to an EC2 Instance

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "*.sh"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.21.4"

      - name: Build Go project
        run: go build -o server  ./cmd/server

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker image using Docker Compose
        run: |
          docker-compose build
          docker-compose push

  deploy_to_ec2:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/Cloudsine/VirusScanGateway
            git pull
            sudo docker-compose pull
            sudo docker-compose down
            sudo docker-compose up -d
            sudo docker container prune -f
            sudo docker image prune -f
      - name: Wait for App to be Ready
        run: |
          counter=0
          while ! curl -s https://virusscanapi.lat/
          do
            counter=$((counter+1))
            if [ $counter -gt 30 ]
            then
              echo "Failed to connect to app after 30 attempts."
              # Perform any additional cleanup or logging here
              exit 1
            fi
            echo "Waiting for app to be ready..."
            sleep 10
          done
          echo "Connected to app successfully."
